# Generated by Django 3.2.9 on 2021-11-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='details',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
